### PR TITLE
[SEG] Comments

### PR DESCRIPTION
**Pull request by Moonzyyy**
#### What does this implement/fix? Explain your changes

Added comments, preparing for tomorrow's meeting.

### CODE REVIEW

**Review by TonyBagnall — APPROVED** [review]

**Comment by Moonzyyy** [comment]
Just moved my working folder to _wip and also changed segmentation to series transformer. Had a massive error happening with top down approach which is also now fixed.

**Comment by MatthewMiddlehurst** [comment]
The old versions seem to be in the package still, you can see both in the diff.

**Comment by MatthewMiddlehurst** [comment]
Also FYI, tests do not run when PRing into branches other than main currently.

**Comment by Moonzyyy** [comment]
> The old versions seem to be in the package still, you can see both in the diff.

Apologies! Should all be removed now.

**Review by TonyBagnall — APPROVED** [review]
lets get this in and we can take a look locally, might want to restructure it a bit

**Pull request merged**
